### ISSUE TITLE
Change active theme name from "CJET" to "Learn" or similar

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-inndev#101]

**Comment by joshdarby** [comment]
Is this something absolutely necessary? I'm worried that by renaming it, anyone new who dives into the code will be wondering why all of the theme functions are prefaced with `cjet_`, unless we spend the time to update all of the function names and variables to reflect the new theme name.

**Comment by MirandaEcho** [comment]
Gotcha, I will clarify. Thanks!

**Comment by benlk** [comment]
This can be done without changing the directory name by changing this line:

https://github.com/INN/umbrella-inndev/blob/master/wp-content/themes/cjet/style.css#L2

We can expand the documentation in https://github.com/INN/umbrella-inndev/blob/master/wp-content/themes/README.md as well, for theme devs.

**Comment by joshdarby** [comment]
Right, but if we're going to change a portion of the naming for the theme, I was wondering if it was in the scope to change everything since that's probably best practice.

**Comment by MirandaEcho** [comment]
@benlk and @joshdarby - what are our final thoughts here? Can we just change the theme name as it displays to the content editors to avoid their confusion?

**Comment by joshdarby** [comment]
@benlk What do you think? I'm still in favor of doing all or nothing but interested in your thoughts.

**Comment by benlk** [comment]
I think it's fine to just change the theme name. We can put a historical note in the README referring to this issue, and make sure that the `Text Domain` string in the readme is set to `cjet`. 

The user-facing code should be consistent with the user-facing code, and the dev-facing code should be consistent with the dev-facing code.

Not updating the function names saves us time, and doens't affect the readers.

**Comment by joshdarby** [comment]
> make sure that the Text Domain string in the readme is set to cjet.

@benlk Did you mean inside of `style.css`?

**Comment by benlk** [comment]
er, yes. In `style.css` is where WordPress would care about it, but it should also be mentioned in the theme readme.

**Comment by joshdarby** [comment]
@benlk `cjet` doesn't have a readme which is why I was confused 😬

**Comment by benlk** [comment]
Might be time to make one. 🤷‍♂

**Comment by joshdarby** [comment]
@benlk I'll create an issue for it.

**Comment by joshdarby** [comment]
@MirandaEcho This is deployed on staging.
