### ISSUE TITLE
Update homepage image and CTA

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-inndev#114]
1. Go to: inn.org

RESULT: image of people looking at a computer with CTA "The INN Futures Fellowship..."

EXPECT: replace with this image:
![image](https://user-images.githubusercontent.com/15877728/62835969-77b4fe80-bc1b-11e9-8a5a-0309a2ce3076.png)

CTA: 
INN Business Intensive 2019
Podcast Your Way to New Audiences and New Revenue
Sept. 11, 2019 in New Orleans
Orange button that says "LEARN MORE":
![image](https://user-images.githubusercontent.com/15877728/62835939-37558080-bc1b-11e9-8f7c-7fce073b3736.png)

Here's the mockup (**except make the "Learn more" a button,** please!):
![image](https://user-images.githubusercontent.com/15877728/62835955-581dd600-bc1b-11e9-8c14-a93d699f8992.png)

All links should go to: https://inn.org/inn-business-intensive-2019/

**Comment by kaylima** [comment]
FYI @MirandaEcho

**Comment by benlk** [comment]
Closing this because it was done, and then removed.
