### ISSUE TITLE
Build template for presenting saved links on member sites

### ISSUE THREAD

**Issue by benlk** [INN/umbrella-inndev#125]
- [x] dedicated URL param to get this template
- [x] display published saved links
    - [x] no need for presentation at this point, just need the links on the page
    - [x] generic enough that it can be used on other projects, so the category of saved links should be drawn from a URL parameter rather than be hardcoded
    - [x] Lens on Lightfoot branding, provided by INN, saved as a Saved Links category metadata
    - [x] description text provided by iNN, saved as Saved Links category metadata
    - [x] "more" link that takes people to the category page on the landing page, which might need to be something other than the category archive page, so it should be configurable

**Comment by benlk** [comment]
The tag to use: https://amplify.inn.org/wp-admin/term.php?taxonomy=lr-tags&tag_ID=2&post_type=rounduplink&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dlr-tags%26post_type%3Drounduplink

The Tag presents the following metadata:

- Name
- slug
- description, which is a plain text field without TinyMCE. 

Questions:
- [ ] does the plain text field accept HTML?
- [ ] do the various portions of the frontend output HTML?
- [ ] Can we build the widget template in https://github.com/INN/umbrella-inndev/issues/125 to output santitized HTML from this field?

**Comment by joshdarby** [comment]
>  does the plain text field accept HTML?

Nope.
