### ISSUE TITLE
Style embed for Amplify content on member sites

### ISSUE THREAD

**Issue by benlk** [INN/umbrella-inndev#127]
Should be responsive for horizontal and vertical presentations, and work at all aspect ratios. Scrolling is expected for the list of items.

**Comment by benlk** [comment]
from https://github.com/INN/umbrella-inndev/pull/130/files#r356834766:

Look at what gets enqueued in `wp_head` and revise as necessary in order to make sre that the embed is as lightweight as possible.

**Comment by joshdarby** [comment]
> Look at what gets enqueued in wp_head and revise as necessary in order to make sre that the embed is as lightweight as possible.

Merged in #133
