### ISSUE TITLE
GiveWP configuration

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-inndev#145]
RESULT: INN.org has GiveWP installed, but it's not fully configured
EXPECT: Create a new GiveWP form o update existing one (it's not being used yet) to have the following features:
1. Default to recurring donations
2. Option for donors to cover the processing fee https://givewp.com/addons/fee-recovery/
3. Fields for Email, First name, Last name
4. Connected to INN's Stripe account (the same account where the Gravity Forms donations go now)
5. Multi-level donations ($60, $120, $350) + fill in the blank field
6. MailChimp add-on so folks can sign up for our lists when they donate

Examples: 
- https://donate.propublica.org/give/141278/#!/donation/checkout
- https://support.texastribune.org/donate

**Comment by joshdarby** [comment]
@kaylima Do we want to configure this on staging first or just do it on prod?

**Comment by joshdarby** [comment]
> MailChimp add-on so folks can sign up for our lists when they donate

What list should they be signed up for?

**Comment by joshdarby** [comment]
- [ ] Default to recurring donations
- [ ] Option for donors to cover the processing fee https://givewp.com/addons/fee-recovery/
- [ ] Fields for Email, First name, Last name
- [ ] Connected to INN's Stripe account (the same account where the Gravity Forms donations go now)
- [ ] Multi-level donations ($60, $120, $350) + fill in the blank field
- [ ] MailChimp add-on so folks can sign up for our lists when they donate

Here's the form so far:

https://inn.org/donation-form-2-0/

**Comment by joshdarby** [comment]
Looks like we'll need to update the recurring donations add-on.

> Attention: Give 2.5.0+ requires the latest version of the Recurring Donations add-on to process payments properly with Stripe. Please update to the latest version add-on to resolve compatibility issues. If your license is active, you should see the update available in WordPress. Otherwise, you can access the latest version by logging into your account and visiting your downloads page on the GiveWP website.

I'll update it on staging first to make sure no weirdness happens.

**Comment by joshdarby** [comment]
I don't see anything obviously wrong with staging after updating Give and its add-ons. I'll go ahead and backup prod them update them there.

**Comment by kaylima** [comment]
@joshdarby re: MailChimp:
- Nerd Alert
- INNovation

**Comment by joshdarby** [comment]
@kaylima Which list is INNovation?

![Screen Shot 2020-02-24 at 3 29 43 PM](https://user-images.githubusercontent.com/18353636/75188653-81ff9b80-571a-11ea-98be-d6e67e279f44.png)
