### ISSUE TITLE
GiveWP front-end tweaks

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-inndev#146]
Go to: https://inn.org/donation-form-2-0/

**1. RESULT:**
![Screen Shot 2020-02-24 at 2 35 50 PM](https://user-images.githubusercontent.com/15877728/75193314-3b5a7300-5713-11ea-99aa-38a0f37708cc.png)

Something wonky is happening with the "State" field where it's not tall enough.

**EXPECT:** have the field height match the field next to it so you can see the "state" label.

**2. RESULT:** Button style = bold font and lots of padding
**EXPECT:** Button font = regular weight and 10px padding all around.

**2. RESULT:** Donation amount at top of the form is on it's own line
**EXPECT:** If possible, ombine onto the same line as donation level or put them side-by-side buttons to save space. For example, this would be the right side:

![Screen Shot 2020-02-24 at 2 41 20 PM](https://user-images.githubusercontent.com/15877728/75193586-c471aa00-5713-11ea-9bec-0554dea86b78.png)

Let me know if you run into any issues with this or want to strategize how it looks! Thanks.

**Comment by joshdarby** [comment]
> Something wonky is happening with the "State" field where it's not tall enough.

@kaylima What browser/width do you see that happening on? It might be because the state field is a dropdown instead of a text input

<img width="1376" alt="Screen Shot 2020-02-25 at 10 27 57 AM" src="https://user-images.githubusercontent.com/18353636/75261794-96df3c00-57b9-11ea-9142-6405ac32d644.png">

**Comment by joshdarby** [comment]
> 2. RESULT: Donation amount at top of the form is on it's own line
EXPECT: If possible, ombine onto the same line as donation level or put them side-by-side buttons to save space. For example, this would be the right side:

@kaylima Same question as above: what screen size and browser are you seeing that on? I see the custom amount button on the same line as the others from 886px and up

![Screen Shot 2020-02-25 at 10 56 06 AM](https://user-images.githubusercontent.com/18353636/75264538-8b8e0f80-57bd-11ea-83f5-2066149c589f.png)

**Comment by kaylima** [comment]
@joshdarby the state issue is happening on my laptop on Chrome. Maybe it's a bug? we can screenshare if needed to figure that out...

re: the donation items. the image I sent you was an example of what could be created so that the amount would be on the left. I don't know what size I grabbed it at, but it was likely mobile size.... 

It's on 1 line most of the time for me, too.

**Comment by joshdarby** [comment]
> the state issue is happening on my laptop on Chrome. Maybe it's a bug? we can screenshare if needed to figure that out...

@kaylima Yea, screensharing might be a good idea here to save time.

**Comment by joshdarby** [comment]
> the state issue is happening on my laptop on Chrome. Maybe it's a bug? we can screenshare if needed to figure that out...

@kaylima Yea, screensharing might be a good idea here to save time.

**Comment by kaylima** [comment]
Next round of front-end updates (updated or new code in bold):

1. New reverse widget styling:

#sidebar .widget.rev {
    **padding: 24px;**
    **border: 8px solid #0089bb;**
    **font-family: "Merriweather", georgia, serif;**
    **font-weight: 300;**
    

2. Update the Give buttons for [our new donate page](https://inn.org/?page_id=884254&preview=true)

- Make the padding 12px for all Give buttons.
- Make the "DONATE NOW" button at the bottom of the form orange (#ff8b4d), it's currently blue.
![Screen Shot 2020-04-27 at 2 59 22 PM](https://user-images.githubusercontent.com/15877728/80420287-c123a780-8897-11ea-8ffe-4d989651e7b8.png)

- The donation levels at the top of the form **can stay blue!**
![Screen Shot 2020-04-27 at 2 58 45 PM](https://user-images.githubusercontent.com/15877728/80420202-9fc2bb80-8897-11ea-8ac5-f2bfe60324f5.png)


2. Go to inn.org and look at the donate/subscribe buttons in top right, orange.
RESULT: 
![Screen Shot 2020-04-27 at 2 55 22 PM](https://user-images.githubusercontent.com/15877728/80419907-288d2780-8897-11ea-99b0-2a5370931f31.png)

EXPECT:
"DONATE" - same orange color
"SUBSCRIBE TO OUR NEWSLETTERS" - blue 
(make the button plural, right now it says "newsletter", singular)

Let me know if you have any Qs!

**Comment by benlk** [comment]
#1: widget styles

For the reverse widget styling, I'm guessing that you'll want to change the background color and font colors to match the new blue border?

![Screen Shot 2020-04-27 at 23 41 14](https://user-images.githubusercontent.com/1754187/80444853-c0fbca00-88e0-11ea-9363-d80aa57e4714.png)

#2: 

https://github.com/INN/inn/pull/128 has been deployed to staging, with a recreation of the live form now available for review at https://inndev.staging.wpengine.com/?page_id=862706&preview=true

#3: header buttons

![Screen Shot 2020-04-27 at 23 45 56](https://user-images.githubusercontent.com/1754187/80445067-5ac37700-88e1-11ea-8725-df5739902a25.png)

Now on https://inndev.staging.wpengine.com; I'm assuming that we do _not_ want to have mismatched button heights. Should this be solved by making the shorter button taller, or by changing the text on the buttons?

**Comment by benlk** [comment]
Now :deployed: with https://github.com/INN/umbrella-inndev/commit/0928f09592d4f90dc6ff6926b90550051ad8c4e2
