### ISSUE TITLE
Add Subscribe and Donate buttons to mobile

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-inndev#168]
- . Add the buttons into the mobile hamburger menu on mobile, at the top or bottom of the existing menu items there. This would take around 4 hours.

I have asked if they would like them at the top or bottom and will post the response here when I hear back, but we should be able to get started for now.

**Comment by MirandaEcho** [comment]
- Heard back: Sharene requests the buttons show at the bottom of the menu on mobile.

**Comment by benlk** [comment]
- [ ] add the Header Widget Area to the end of the mobile nav, with styles that keep it approximately the same appearance.
