### ISSUE TITLE
QA Review - Mobile

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-inndev#28]
iPhone 5/6:

- [x] Search prompt "Search our resources and guides" gets cut off. Change to just "Search our resources".
- [x] Remove photo credit on mobile

**Comment by benlk** [comment]
> Search prompt "Search our resources and guides" gets cut off. Change to just "Search our resources".

is that only on mobile, or also on Desktop?

**Comment by kaylima** [comment]
```
Search prompt "Search our resources and guides" gets cut off. Change to just "Search our resources".

is that only on mobile, or also on Desktop?
```
Only on Mobile, unless it's easiest to change across both, then both. Whichever takes less time.

**Comment by benlk** [comment]
It was easiest to change both.
