### ISSUE TITLE
QA Priorities List

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-inndev#29]
## inn.org

HOMEPAGE:

High priority (to be done in the next 2 hours):
- [x] remove nav underlines
- [x] make top tags consistent for link hover colors, and title case,  lose :visited link treatment
- [x] :From INN" and "From INN Members" go back to lighter text (to match the current INN MISSION title)
- [x] more space under the FROM INN and FROM INN MEMBERS images
- [x] #main-nav.nav text-align right;

Medium Priority (over the next couple of days):
- [x] darker blue on rollover for donate button (same as “Go” in global nav search)
- [ ] get kay rules for excerpts: 355 char, 55 words for the saved links and announcement excerpt, and 35 words for the events (don’t change how they are currently - they look great!)
- [x] global nav font size slightly smaller -> to match mockup
- [x] enable social buttons in global nav next to search - they should be white (per mockup)
- [x] more space above and below the INN logo: increase margin-top and margin-bottom
- [x] Donate button in mobile nav = blue

INTERIOR:

High priority (to be done in the next 2 hours):
- [x] li + li ::before becomes .widget + .widget::before
- [x] have an example page ready for Sue with a newsletter signup in sidebar
- [x] put the subnav above the sidebar

Medium Priority (over the next couple of days):
- [x] remove the span8 margin-left on #content.span8;
- [x] (MOBILE)member pages overflow 100% width

## learn.inn.org:

High priority (to be done in the next 2 hours):
- [x] new logos from Dropbox for learn: top of list
- [x] update global nav
- [x] remove the "don't miss"
- [x] add main nav items to top right, above the hero image (per mockup)

**Comment by benlk** [comment]
high-priority items done, adding this to medium-priority:

- [ ] copy blue-nav styles from inn.org into learn.inn.org theme

**Comment by kaylima** [comment]
inn.org:
- [ ] Event description -> not a link
- [ ] Events title -> link to all events (the entire title bar go to black on hover)
- [ ] Homepage alert should be global (show on homepage and interior pages)

learn:
- [ ] main nav links -> remove underline
- [ ] footer should be the same as inn.org
- [ ] remove opacity on hover for learn logo in header

**Comment by benlk** [comment]
>  learn interior page styles should match inn.org ex.: https://learn-inn-org.inndev.staging.wpengine.com/guides/fundraising/individual-giving/resources/

I'm gonna put that off until Friday.

**Comment by benlk** [comment]
Closing in favor of https://github.com/INN/umbrella-inndev/issues/31 and https://github.com/INN/umbrella-inndev/issues/30, and other issues as they are created.
