### ISSUE TITLE
update sticky nav button color

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-inndev#52]
1. Go to inn .org.
2. Scroll down and activate the sticky nav.
3. Look at "Support Nonprofit Newsrooms" button.

RESULT: red

EXPECT: should be updated to whatever our CTA color will be (see #50)

**Comment by kaylima** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [See progress on GitHub (see description)](https://trello.com/c/U48nBM76/6-see-progress-on-github-see-description)

**Comment by kaylima** [comment]
@tylermachado this is a high priority, has this been completed already? this can be blue or the orange

**Comment by kaylima** [comment]
@tylermachado (bump) has this been updated already?

**Comment by tylermachado** [comment]
@kaylima I did update this locally to orange. I have not pushed up any changes while waiting for approval on the mockup from Sue/Jules.
