### ISSUE TITLE
old events need color updated

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-inndev#54]
1. Go to inn.org.
2. Look at the calendar.

RESULT: old dates still have an old faded cyan look 

EXPECT: color needs to be updated

**Comment by tylermachado** [comment]
Is this still the case?

**Comment by kaylima** [comment]
yes, please

**Comment by kaylima** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [See progress on GitHub (see description)](https://trello.com/c/U48nBM76/6-see-progress-on-github-see-description)
