### ISSUE TITLE
homepage "mockup" updates

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-inndev#56]
![Screen Shot 2018-12-17 at 6.02.09 PM.png](https://images.zenhubusercontent.com/59250b9c51aa2c30577f4368/47d23f79-5387-42b5-8255-6af8ec655136)

**Comment by kaylima** [comment]
Is it possible to bring in the standard largo meta nav that has the search way up a the top? Having it in the nav is really causing nav issues... Let me know your thoughts on the easiest way to improve.

**Comment by benlk** [comment]
Removing this line in `functions.php` will bring back Largo's `partials/nav-global.php`:

https://github.com/INN/inn/blob/d719602e3e7229bc83407635ce51c9d6aefb84fd/functions.php#L8

Here's what that looks like in the current theme, as of https://github.com/INN/inn/pull/93#issuecomment-447969018

<img width="1233" alt="screen shot 2018-12-17 at 8 08 38 pm" src="https://user-images.githubusercontent.com/1754187/50125630-baaf0580-0237-11e9-999c-3043ffeb01ca.png">

There's a lot of blank space up there, and we'd need to remove the black bar portion anyways.

If some items from INN's current main menu could be consolidated or rearranged, there'd be room for the search box in the main nav even at narrower desktop sizes.
