### ISSUE TITLE
Learn Site Header Branding Updates

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-inndev#62]
See Wireframe here for design: https://drive.google.com/drive/folders/16we8eCY2DZR2eVTDuz3qCQI0k-kxDf1Q

Edits from wireframe:
- [x] Make sure "About" is in line with search bar
- [x] Leave out mosaic from search bar for now

**Comment by MirandaEcho** [comment]
@Josh this is ready to be picked up again, see linked wireframe for design.

**Comment by joshdarby** [comment]
@MirandaEcho Can you get me the new version of the Learn logo that is in the design?

**Comment by kaylima** [comment]
@joshdarby https://www.dropbox.com/s/7v0vkzdsz0aqn6z/learn%20logo%202019.svg?dl=0 Let me know if you have any issues with this file or if you need another format other than SVG. Thanks! and FYI @MirandaEcho

**Comment by joshdarby** [comment]
@kaylima Is it possible to get the logo in a png?

**Comment by kaylima** [comment]
![learn logo PNG](https://user-images.githubusercontent.com/15877728/58640899-48971e00-82b7-11e9-86e3-7427c715f69a.png)

**Comment by joshdarby** [comment]
Thank you!

**Comment by joshdarby** [comment]
Required configuration changes for header:

- [ ] Update all instances of site logo in Theme Options
- [ ] Update `Main Navigation` menu to include `Topics`, `Resources`, and `About` links
- [ ] Update `More from INN` menu to include `Institute for Nonprofit News`, `INN Labs`, `Amplify, and `Other INN Links` links
- [ ] Uncheck `Show a button in the top header to link to your donation page or form.`

**Comment by joshdarby** [comment]
@benlk @MirandaEcho This has been merged and is deployed on the staging environment if anyone wants to take a look: https://learn-inn-org.inndevlearn.wpengine.com/
