### ISSUE TITLE
Add internal-only fields to content pages

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-inndev#66]
- [ ] Date of initial publishing (vesrus date of last page edit)
- [ ] Author/Source of content (versus the individual who published the page)

These should only be viewable on the edit screen and not publicly on the site.

**Comment by MirandaEcho** [comment]
@joshdarby - remind me where we left off on this again please?

**Comment by joshdarby** [comment]
@MirandaEcho I think I assigned this to myself but got moved into other work before I had a chance to actually start on it.

**Comment by joshdarby** [comment]
@MirandaEcho can you explain this more? 

> Date of initial publishing (vesrus date of last page edit)

WordPress automatically shows the actual date the post was published. Did we want to flip flop this to show the date it was last edited?

![Screen Shot 2019-05-23 at 10 45 00 AM](https://user-images.githubusercontent.com/18353636/58262318-12521f80-7d48-11e9-8f30-8215e04735db.png)

**Comment by MirandaEcho** [comment]
@joshdarby they want both.  Because the content is largely written by outside sources and pasted in, it's helpful for them to know when the original page of content was created/updated (probably via manual input and call it "content date" or something), as well as the last page update collected by Wordpress.  Both should only display internally and not on the page itself. Does that make sense?

**Comment by joshdarby** [comment]
@MirandaEcho Is something like this ok? Just a metabox that displays the last user who updated the post/page and the date it was last modified?

![Screen Shot 2019-05-28 at 3 59 06 PM](https://user-images.githubusercontent.com/18353636/58508238-9b5ec180-8161-11e9-90c7-fbefdb2cddbe.png)

**Comment by MirandaEcho** [comment]
@joshdarby yes that works, but we'll also need the one for manually entering the content date, as mentioned above. Thanks!

**Comment by joshdarby** [comment]
@MirandaEcho How does this look?

![Screen Shot 2019-05-28 at 4 53 41 PM](https://user-images.githubusercontent.com/18353636/58511662-42932700-8169-11e9-84ee-dc98c7cd830f.png)

The `Content Date` field works as a date field.

![Screen Shot 2019-05-28 at 4 54 20 PM](https://user-images.githubusercontent.com/18353636/58511661-42932700-8169-11e9-8b56-4726a39cc4f3.png)

**Comment by MirandaEcho** [comment]
@joshdarby, it looks good but the author field is editable right, so they can record the author/source of the content rather than the wordpress account who put it in there?

**Comment by joshdarby** [comment]
@MirandaEcho In the `Last Edited` metabox, it is not editable. There is an `Authors` metabox right above that has an editable author field. 

![Screen Shot 2019-05-29 at 9 14 57 AM](https://user-images.githubusercontent.com/18353636/58560064-4fa82880-81f2-11e9-879f-c19e0cb178fa.png)

**Comment by MirandaEcho** [comment]
@joshdarby  looks good

**Comment by joshdarby** [comment]
@MirandaEcho Cool! Merged into `staging` in PR #78.
