### ISSUE TITLE
Feedback/suggestion form

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-inndev#68]
Create a form for suggestions or updates from members that:
- [x] Allows members to provide specific resources or updates via links and file attachments.
- [x] Uses positive language.
- [x] Ties feedback to the specific content it was submitted on.
- [x] Has an auto-reply option possible to set expectations for turnaround.
- [ ] Allow separate spaces for design feedback vs content feedback.

**Comment by kaylima** [comment]
@MirandaEcho we typically use Gravity Forms for this on our website... however, I'd check to make sure with Jules that this shouldn't be a NEON form that we embed.

**Comment by MirandaEcho** [comment]
Confirmed with Jules that Gravity Forms is fine for this, rather than Neon.

**Comment by benlk** [comment]
- [ ] When people submit the form, were does the submission go to?
- [ ] Include page URL in form submission somehow

**Comment by MirandaEcho** [comment]
This will probably work to include the page URL: https://www.wpgarage.com/plugins/dynamic-page-url-gravity-forms-wordpress/

**Comment by benlk** [comment]
@MirandaEcho What email address should form submissions be sent to?

**Comment by MirandaEcho** [comment]
Fields:
- [ ] We welcome your suggestions to keep these guides useful and updated. Please use the following space to tell INN about any necessary updates or resources we can add to this repository of information. (large open comment box)
- [ ] File attachment for resources if needed
- [ ] Please let us know if you are an INN member or affiliate. (Radio button box -- with room to put in name of organization: INN member, INN affiliate, Other.)
I would require them to check one of the three to submit, but not require them to enter the name of their organization.
- [ ] If you would like an individual response following up on your suggestion, give us your email address. Please note that INN is a fast-growing organization with many projects underway, so you may not hear back quickly. (Optional email address field)  
- [ ] Internal field to record origin page URL

Waiting on confirmation, but for now info@inn.org with a subject of "Suggestion for Learn Website" or something similar.

**Comment by benlk** [comment]
> File attachment for resources if needed

This is not advisable, for a lot of reasons which mainly have to do with bad actors filling our website storage with undesirable files.

Instead, can we implore people to provide links to external content? Something like this:

> We welcome your suggestions to keep these guides useful and updated. Please use the following space to tell INN about any necessary updates or resources we can add to this repository of information.
> 
> Should we split a subtopic out for deeper coverage? Should a resource be linked to? Let us know your ideas for improving this guide, and feel free to paste URLs to resources here.

**Comment by MirandaEcho** [comment]
Yes, that makes sense. Good feedback Ben!

**Comment by benlk** [comment]
> Please let us know if you are an INN member or affiliate. (Radio button box -- with room to put in name of organization: INN member, INN affiliate, Other.)

The human filling out this form is not themself an INN member or affiliate organization. Is it okay to change this language to something like:

> Do you work for an INN member or affiliate?
>
> - INN member
> - INN affiliate
> - Not affiliated

followed by show-if-checked text boxes asking which INN member or which affiliate the form-filling person works for.

I'm not sure how we can handle the "Not affiliated" case, because someone may be filling this feedback in by themself or for an unaffiliated organization.

**Comment by benlk** [comment]
Form created: https://learn-inn-org.inndevlearn.wpengine.com/wp-admin/admin.php?page=gf_edit_forms&id=1

Preview: https://learn-inn-org.inndevlearn.wpengine.com/?gf_page=preview&id=1

Now to wedge it into the sidebar.

**Comment by joshdarby** [comment]
@benlk I set up a widget area in this [PR](https://github.com/INN/umbrella-inndev/pull/89) named `guide-sidebar-below-toc`. We can go ahead and merge it if it looks ok to you so you're not blocked from finishing this.

**Comment by benlk** [comment]
I was just looking at that; https://github.com/INN/umbrella-inndev/pull/89/files#r289490167 is my only feedback.

**Comment by benlk** [comment]
Something that won't work: Putting the form inside a `<details>` element: https://learn-inn-org.inndevlearn.wpengine.com/2019/05/31/test-post-for-sidebar/

![Screen Shot 2019-05-31 at 16 37 06 ](https://user-images.githubusercontent.com/1754187/58733367-5b4a4980-83c2-11e9-916b-ce6e9533570c.png)

We can apply the shortcodes filter to Custom HTML widgets, and change the button coloration/appearance.
