### ISSUE TITLE
Homepage Startup Guide Featured Block

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-inndev#70]
Mockup: https://drive.google.com/drive/folders/16we8eCY2DZR2eVTDuz3qCQI0k-kxDf1Q

Notes/changes from mockup:
- Use icon instead of mosaic
- Will link to startup guide page

**Comment by MirandaEcho** [comment]
@joshdarby - this is ready for us to start building out.  Let me know if you have questions or need more info on anything.

**Comment by benlk** [comment]
What icon are we supposed to use here?

**Comment by benlk** [comment]
And is this supposed to be editable, or can it be hardcoded?

**Comment by benlk** [comment]
Note on implementation: This is a widget area with a number of image widgets, each set to link tot he relevant area.

**Comment by MirandaEcho** [comment]
@ben - Use your best judgement on the icon for now.  This should be editable so that it can be swapped out for other featured content in the future. Great question, thank you!
