### ISSUE TITLE
Custom sidebar for content pages

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-inndev#76]
Wireframe: 
![Guide Detail v6](https://user-images.githubusercontent.com/48263361/58287989-054d2480-7d78-11e9-941b-14e803de0c6a.png)

- Custom sidebar that uses menus and how to associate it to sets of pages knowing that a page could be referenced in multiple sidebars/menus
- "Contribute" section in wireframe will actually be below the ToC and will say "Suggestions" instead of contribute.

**Comment by joshdarby** [comment]
@kaylima Can you send over the icon that goes before `Related Resources`, along with the `prev` and `next` icons, please?

**Comment by MirandaEcho** [comment]
@joshdarby To clarify again, this issue is for the sidebar only (we're scrapping the document section on the old pages), not the other page elements like related resources.  Previous and next buttons have a separate issue, but I'll see if I can get those arrow icons.

**Comment by joshdarby** [comment]
@kaylima @MirandaEcho Did we decide where we want the `Related Resources` to go now?

**Comment by MirandaEcho** [comment]
@joshdarby We can disable the section on the new templates. It sounds like the site will mostly be a fresh start with added content, and the pages that currently exist will only be there for archive purposes, so we're fine with the section going away.
