### ISSUE TITLE
Add optional "Guide Title" field to guide/article pages

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-inndev#77]

**Comment by joshdarby** [comment]
@MirandaEcho Can we get more info on this?

**Comment by MirandaEcho** [comment]
@joshdarby take a look at the [design mockup](https://drive.google.com/drive/folders/16we8eCY2DZR2eVTDuz3qCQI0k-kxDf1Q).

The "Guide Title" field needs to be added, and it needs to be optional so it only shows when in use. Does that help? Let me know if I can clarify anything else!

**Comment by benlk** [comment]
Some more questions:

- Is "Guide title" supposed to be consistent across all pages within a guide?
- Can a page be in multiple guides or just one?
- Is the guide title basically the title of the shared parent page between all pages in that guide?

**Comment by benlk** [comment]
Based on discussion, we'll use Top Term for now, and switch to a custom metabox afterwards if Top Term is insufficient for Learn's purposes.

- [ ] make sure `largo_maybe_top_term()` is on all post templates in this theme.
