### ISSUE TITLE
Configuration changes to production learn.inn.org

### ISSUE THREAD

**Issue by benlk** [INN/umbrella-inndev#82]
- [x] deploy code changes
- [x] deploy DB changes
- [x] disable job board
- [ ] activate Gutenberg plugin
- [x] activate https://wordpress.org/plugins/simple-page-ordering/

**Comment by joshdarby** [comment]
Header updates configuration changes: https://github.com/INN/umbrella-inndev/pull/87#issuecomment-498266146

**Comment by benlk** [comment]
- [ ] turn off Google Custom Search in **Theme Options > Advanced**

**Comment by benlk** [comment]
- [ ] make sure homepage widgets are set up

**Comment by benlk** [comment]
- [ ] upgrade the two relevant users to admin status, so they can manage widgets

**Comment by joshdarby** [comment]
**Link main breadcrumb link to Learn home instead of INN home**

- [ ] `Settings->Breadcrumb NavXT` -> `Home Breadcrumb: Home Template` 
Update to `<a title="Go to Institute for Nonprofit News: Learn" href="https://learn.inn.org" class="%type%">INN Learn: Home</a>`
