### ISSUE TITLE
Homepage "Explore Topics" section

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-inndev#84]
"Explore Topics" section of homepage based on wireframe: https://drive.google.com/drive/folders/16we8eCY2DZR2eVTDuz3qCQI0k-kxDf1Q

Notes/Requirements:
- [ ] Number of topics is dynamic and will need to be easily adjusted and new topics with icons easily added
- [ ] Icons should be a bit bolder/heavier than they are on the mockup

**Comment by benlk** [comment]
It turns out that we have an account with https://www.flaticon.com/, so I'll poke around there, but we'll need to know from the Learn folks what they actually want to have linked there.

**Comment by benlk** [comment]
Dashicons https://developer.wordpress.org/resource/dashicons/#thumbs-down would be wonderful to use, but they aren't available to us as image or SVG; only as fonts.

We could use [The Noun Project](https://thenounproject.com/accounts/pricing/), but that would require attribution for most licenses. https://thenounproject.com/public-domain-nouns/uploads/ contains public-domain icons that would not require attribution, according to https://thenounproject.zendesk.com/hc/en-us/articles/200509798-What-licenses-do-you-use-
