### ISSUE TITLE
Create separate template for articles vs guides

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-inndev#85]
Article template will be the same, but will not have previous and next navigation buttons at the bottom.

**Comment by joshdarby** [comment]
This is merged into staging in PR #88.

**Comment by benlk** [comment]
- [ ] remove attachments code from article template
- [ ] add sidebar to article template
- [ ] verify that sidebar is now same in code in guide/article templates
- [ ] put that sidebar code into a partial, to deduplicate code and improve maintainability
